sudo: required
services:
        - docker
before_install:
        - docker build -t meherbabu/react-test -f ./client/Dockerfile.dev ./client

script:
        - docker run meherbabu/react-test npm test -- --coverage

after_success:
        - docker build -t meherbabu/multi-client ./client
        - docker build -t meherbabu/multi-worker ./worker
        - docker build -t meherbabu/multi-server ./server
        - docker build -t meherbabu/multi-nginx ./nginx
#login to docker cli
        - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
        - docker push meherbabu/multi-client
        - docker push meherbabu/multi-worker
        - docker push meherbabu/multi-server
        - docker push meherbabu/multi-nginx
